# 02. 의류 아이템 인식하기

## 코드부터 작성하기

구현 모델: 28x28 흑백 이미지를 입력받아 셔츠, 바지, 드레스 등의 종류 구별

In [ ]:
import tensorflow as tf

In [ ]:
data = tf.keras.datasets.fashion_mnist
(training_images, training_labels), (test_images, test_labels) = data.load_data()

4422102/4422102 [==============================] - 0s 0us/step


In [ ]:
training_images = training_images / 255.0
test_images = test_images / 255.0

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

In [ ]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(training_images, training_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5039 - accuracy: 0.8228
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3801 - accuracy: 0.8621
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3376 - accuracy: 0.8762
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3138 - accuracy: 0.8857
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2967 - accuracy: 0.8911


## 코드 분석하기

### 모듈 불러오기

In [ ]:
import tensorflow as tf

## 데이터 준비하기


*   입력 데이터 = images
*   출력 데이터 = labels

In [ ]:
data = tf.keras.datasets.fashion_mnist
(training_images, training_labels), (test_images, test_labels) = data.load_data()

4422102/4422102 [==============================] - 0s 0us/step


In [ ]:
training_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,
          1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,
          0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,
         10,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 155, 236, 207, 178, 107, 156, 161, 109,  64,  23,  77, 130,
         72,  15],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,
         69, 207, 223, 218, 216, 216, 163, 127, 121, 122, 146, 141,  88,
        172,  66],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   1,   1,   0,
        200, 232, 232, 233, 229, 223, 223, 215, 213, 164, 127, 123, 196,
        229,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        183, 225, 216, 223, 228, 235, 227, 224, 222, 224, 221, 223, 245,
        173,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        193, 228, 218, 213, 198, 180, 212, 210, 211, 213, 223, 220, 243,
        202,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   3,   0,  12,
        219, 220, 212, 218, 192, 169, 227, 208, 218, 224, 212, 226, 197,
        209,  52],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,   0,  99,
        244, 222, 220, 218, 203, 198, 221, 215, 213, 222, 220, 245, 119,
        167,  56],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   4,   0,   0,  55,
        236, 228, 230, 228, 240, 232, 213, 218, 223, 234, 217, 217, 209,
         92,   0],
       [  0,   0,   1,   4,   6,   7,   2,   0,   0,   0,   0,   0, 237,
        226, 217, 223, 222, 219, 222, 221, 216, 223, 229, 215, 218, 255,
         77,   0],
       [  0,   3,   0,   0,   0,   0,   0,   0,   0,  62, 145, 204, 228,
        207, 213, 221, 218, 208, 211, 218, 224, 223, 219, 215, 224, 244,
        159,   0],
       [  0,   0,   0,   0,  18,  44,  82, 107, 189, 228, 220, 222, 217,
        226, 200, 205, 211, 230, 224, 234, 176, 188, 250, 248, 233, 238,
        215,   0],
       [  0,  57, 187, 208, 224, 221, 224, 208, 204, 214, 208, 209, 200,
        159, 245, 193, 206, 223, 255, 255, 221, 234, 221, 211, 220, 232,
        246,   0],
       [  3, 202, 228, 224, 221, 211, 211, 214, 205, 205, 205, 220, 240,
         80, 150, 255, 229, 221, 188, 154, 191, 210, 204, 209, 222, 228,
        225,   0],
       [ 98, 233, 198, 210, 222, 229, 229, 234, 249, 220, 194, 215, 217,
        241,  65,  73, 106, 117, 168, 219, 221, 215, 217, 223, 223, 224,
        229,  29],
       [ 75, 204, 212, 204, 193, 205, 211, 225, 216, 185, 197, 206, 198,
        213, 240, 195, 227, 245, 239, 223, 218, 212, 209, 222, 220, 221,
        230,  67],
       [ 48, 203, 183, 194, 213, 197, 185, 190, 194, 192, 202, 214, 219,
        221, 220, 236, 225, 216, 199, 206, 186, 181, 177, 172, 181, 205,
        206, 115],
       [  0, 122, 219, 193, 179, 171, 183, 196, 204, 210, 213, 207, 211,
        210, 200, 196, 194, 191, 195, 191, 198, 192, 176, 156, 167, 177,
        210,  92],
       [  0,   0,  74, 189, 212, 191, 175, 172, 175, 181, 185, 188, 189,
        188, 193, 198, 204, 209, 210, 210, 211, 188, 188, 194, 192, 216,
        170,   0],
       [  2,   0,   0,   0,  66, 200, 22

In [ ]:
training_labels[0:5]

array([9, 0, 0, 3, 0], dtype=uint8)

## 데이터 정규화하기

0-255 값의 데이터를 0-1의 범위로 정규화

In [ ]:
training_images = training_images / 255.0
test_images = test_images / 255.0

In [ ]:
training_images[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

### 모델 구성하기

입력(28x28) </br>
-> Flatten(입력된 2차원 데이터를 1차원 배열로 재구성), 784 </br>
-> Dense(입력된 784 길이의 배열을 연산 후 128 길이의 배열로 출력) + Relu, 128 </br>
-> Dense(입력된 128길이의 배열을 연산 후 softmax를 통해 10개의 확률로 출력) + SoftMax, 10 </br>
-> 출력(10)


*   **옵티마이저(optimizer)**: Adam(Adaptive Moment Estimation)
*   **손실함수(loss, Loss Function)**: sparse_categorical_crossentropy(0,1,2,3 등의 정수 값의 라벨에 대한 다중 분류 손실함수)

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

In [ ]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

### 모델 학습하기
tf.keras.Model.fit(x, y)


*   Input = training_images
*   ouput = training_labels
*   epochs = 학습의 반복 수



In [ ]:
model.fit(training_images, training_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.4970 - accuracy: 0.8252
Epoch 2/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.3776 - accuracy: 0.8646
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3377 - accuracy: 0.8773
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3127 - accuracy: 0.8858
Epoch 5/5
1875/1875 [==============================] - 8s 5ms/step - loss: 0.2971 - accuracy: 0.8894


### 예측하기

In [ ]:
model.evaluate(test_images, test_labels)

313/313 [==============================] - 1s 2ms/step - loss: 0.3715 - accuracy: 0.8633


[0.37151914834976196, 0.8633000254631042]


* loss(error, 손실) = 0.37
* accuracy(정확도) = 0.86

## 모델 출력 살펴보기

In [ ]:
classifications = model.predict(test_images)
print(classifications[0])
print(test_labels[0])

313/313 [==============================] - 1s 2ms/step
[5.9600575e-06 1.0351787e-07 2.6862290e-06 3.9447536e-07 2.4955700e-05
 6.7921299e-03 1.3235795e-05 4.8533618e-01 1.6399517e-03 5.0618428e-01]
9


모델은 라벨 0-9 에대한 확률을 출력한다. 라벨 9의 확률이 0.506으로 가장 높아 실제 정답인 9와 일치한다.

## Overfitting (과대적합)

epoch를 50번으로 늘려 과대적합 현상을 알아보자.

In [ ]:
model.fit(training_images, training_labels, epochs=50)

Epoch 1/50
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2807 - accuracy: 0.8970
Epoch 2/50
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2684 - accuracy: 0.9014
Epoch 3/50
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2603 - accuracy: 0.9030
Epoch 4/50
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2488 - accuracy: 0.9071
Epoch 5/50
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2409 - accuracy: 0.9113
Epoch 6/50
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2316 - accuracy: 0.9130
Epoch 7/50
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2252 - accuracy: 0.9158
Epoch 8/50
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2182 - accuracy: 0.9188
Epoch 9/50
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2135 - accuracy: 0.9202
Epoch 10/50
1875/1875 [==============================] - 10s 6ms/step - loss: 0.20

In [ ]:
model.evaluate(test_images, test_labels)

313/313 [==============================] - 1s 3ms/step - loss: 0.5398 - accuracy: 0.8902


[0.5398319363594055, 0.8902000188827515]

정확도가 0.89였던 훈련데이터에 대해서는 0.96으로 크게 올랐지만 테스트 데이터의 정확도는 0.86에서 0.89로 소폭 성장하였다. 따라서 학습 epoch에 비해 낮은 성능을 보이고 있다.

## Callback으로 과학습 방지하기

텐서플로우의 Callback 함수를 이용하여 학습 도중 95% 이상의 정확도를 보이면 학습을 중지하도록 설계한다.

In [ ]:
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('accuracy')>0.95):
      print("\n 정확도 95%에 도달하여 훈련을 중지합니다.")
      self.model.stop_training = True

model2 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

model2.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

callbacks = myCallback()
model2.fit(training_images, training_labels, epochs=50, callbacks=[callbacks])

Epoch 1/50
1875/1875 [==============================] - 9s 4ms/step - loss: 0.4991 - accuracy: 0.8238
Epoch 2/50
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3759 - accuracy: 0.8633
Epoch 3/50
1875/1875 [==============================] - 9s 5ms/step - loss: 0.3390 - accuracy: 0.8764
Epoch 4/50
1875/1875 [==============================] - 10s 5ms/step - loss: 0.3116 - accuracy: 0.8854
Epoch 5/50
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2944 - accuracy: 0.8916
Epoch 6/50
1875/1875 [==============================] - 9s 5ms/step - loss: 0.2787 - accuracy: 0.8966
Epoch 7/50
1875/1875 [==============================] - 9s 5ms/step - loss: 0.2673 - accuracy: 0.9002
Epoch 8/50
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2549 - accuracy: 0.9054
Epoch 9/50
1875/1875 [==============================] - 8s 5ms/step - loss: 0.2472 - accuracy: 0.9087
Epoch 10/50
1875/1875 [==============================] - 8s 5ms/step - loss: 0.23